spring.application.name=restaurante-api

# Configuración de Base de Datos NeonDB (PostgreSQL en la Nube)
spring.datasource.url=jdbc:postgresql://ep-silent-resonance-acrozb8g-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=neondb_owner
spring.datasource.password=npg_ICxfkh3a6MGw

# Configuración de JPA / Hibernate PostgreSQL (Arranque Rápido)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Configuración Optimizada de Pool de Conexiones HikariCP
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.max-lifetime=1800000
# Configuración JWT (Expiración de Sesión a las 12 horas)
app.jwt.expiration-ms=43200000

